apiVersion: v1
kind: Service
metadata:
  name: flask-server
  labels:
    app: flask-server
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30000
    protocol: TCP
  selector:
    app: flask-server




