{
 "title": "MyDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Flask Server API Calls (count)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "path_counter_total{instance=\"flask-server:5000\", job=\"flask\", path=\"/data_posts\"}",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "path_counter_total{instance=\"flask-server:5000\", job=\"flask\", path=\"/data_vids\"}",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "path_counter_total{instance=\"flask-server:5000\", job=\"flask\", path=\"/posts\"}",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "path_counter_total{instance=\"flask-server:5000\", job=\"flask\", path=\"/vids\"}",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "path_counter_total{instance=\"flask-server:5000\", job=\"flask\", path=\"/\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job='flask'}",
     "legendFormat": "Mem Usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"flask\"}[30s])",
     "legendFormat": "CPU Usage"
    }
   ]
  }
 ]
}