apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana:5.4.3
        name: grafana
        ports:
        - containerPort: 3000
          name: http

        volumeMounts:
          - name: grafana-dashboards
            mountPath: /var/lib/grafana/dashboards

          - name: grafana-datasource
            mountPath: /etc/grafana/provisioning/datasources/default.yaml 
            subPath: datasource.yml

          - name: grafana-dashcfg
            mountPath: /etc/grafana/provisioning/dashboards/default.yaml 
            subPath: dashboard.yml 

          - name: grafana-ini
            mountPath: /etc/grafana/grafana.ini
            subPath: grafana.ini

      volumes:
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards

        - name: grafana-datasource
          configMap:
            name: grafana-datasource

        - name: grafana-dashcfg
          configMap:
            name: grafana-dashcfg

        - name: grafana-ini
          configMap:
            name: grafana-ini

      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 472


