apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    nodePort: 30001
    protocol: TCP
    targetPort: http
  selector:
    app: grafana
