apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - name: prometheus
    nodePort: 30002
    protocol: TCP
    port: 9090
    targetPort: 9090
  type: NodePort
