# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import streamer_pb2 as streamer__pb2


class StreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getPosts = channel.unary_stream(
                '/Streamer/getPosts',
                request_serializer=streamer__pb2.ClientRequest.SerializeToString,
                response_deserializer=streamer__pb2.ServerResponse.FromString,
                )


class StreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getPosts': grpc.unary_stream_rpc_method_handler(
                    servicer.getPosts,
                    request_deserializer=streamer__pb2.ClientRequest.FromString,
                    response_serializer=streamer__pb2.ServerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Streamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Streamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Streamer/getPosts',
            streamer__pb2.ClientRequest.SerializeToString,
            streamer__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
