apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - name: grafana
    nodePort: 30001
    protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
