version: '3'

services: 
 
    flask-server:
        container_name: flask-server    
        build: ./flask-server
        restart: always
        tty: true
        ports:
            - 5000:5000

    grpc-server:
        container_name: grpc-server
        build: ./grpc-server
        restart: always
        tty: true
        expose:
            - "50051"

    grpc-client:
        container_name: grpc-client
        build: ./grpc-client
        restart: always
        tty: true

    
